---

- name: Remove fake-hwclock
  ansible.builtin.apt:
    name: fake-hwclock
    state: absent

- name: Validate RTC communication
  ansible.builtin.command: hwclock -r
  register: validate_rtc
  changed_when: false

- name: Restart timesyncd to ensure system time is up to date
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: Write current system time to RTC
  ansible.builtin.command: hwclock -w
  when: validate_rtc.rc == 0
  changed_when: true

- name: Copy hwclock-set
  ansible.builtin.copy:
    src: hwclock-set
    dest: /lib/udev/hwclock-set
    mode: "0755"
    owner: root
    group: root
