---
- name: OpenAuto Pi Setup
  hosts: all
  become: true
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: CarPi
        use: debian
      notify: Reboot

    - name: Set password
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        password: $6$rounds=656000$zGzJDXD8c6f3Zi23$p4s751WKk3JgCqH4s.f/Em8Ubld3pOUZsrKyOog74oT0Y/YkegG3pnTDwjYCpe.40sLAVXjxXobHj3PezM8C0/

    - name: Install SSH key
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF5Buzvlm9muLrosWs1MfpnecnxzIlSoox1OF8LkRAmD tig@tiga.tech

    - name: Copy OpenAuto configuration
      ansible.builtin.copy:
        src: "{{ item.root + item.path }}"
        dest: /home/{{ ansible_user }}/.openauto/{{ item.path }}
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
        directory_mode: 0755
      loop: >-
        {{ lookup('filetree', '../openauto/', wantlist=True) }}
      loop_control:
        label: "{{ item.path }}"
      when:
        - item.state == 'file'
        - not 'SAMPLE' in item.path
      notify: Restart display-manager # This restarts OpenAuto.

    - name: Create scripts directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/scripts
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      register: scripts_dir

    - name: Copy scripts
      ansible.builtin.copy:
        src: "{{ item.root + item.path }}"
        dest: "{{ scripts_dir.path }}/{{ item.path }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0774
        directory_mode: 0755
      loop: >-
        {{ lookup('filetree', '../scripts/', wantlist=True) }}
      loop_control:
        label: "{{ item.path }}"
      register: copy_scripts

    - name: Add OpenAuto start menu item
      ansible.builtin.copy:
        dest: /home/{{ ansible_user }}/.local/share/applications/OpenAuto.desktop
        content: |
          [Desktop Entry]
          Name=OpenAuto
          Exec=/home/{{ ansible_user }}/Desktop/openauto
          Terminal=false
          Type=Application
          Categories=Utility;
          Encoding=UTF-8
        mode: 0755
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      notify: Restart display-manager

    - name: Install Zero2Go utilities
      ansible.builtin.script: "{{ scripts_dir.path }}/installZero2Go.sh"
      args:
        creates: /home/{{ ansible_user }}/zero2go

    - name: Install Waveshare display utilities
      ansible.builtin.include_role:
        name: waveshare-display-utils

  handlers:
    - name: Reboot
      ansible.builtin.reboot:

    - name: Restart display-manager
      ansible.builtin.service:
        name: display-manager
        state: restarted
